apiVersion: apps/v1

kind: DaemonSet
metadata:
  name: example-daemonset
  namespace: default
  labels:
    k8s-app: example-daemonset
spec:
  selector:
    matchLabels:
      name: example-daemonset
  
  template: # create pods using pod definition in this template
    metadata:
      labels:
        name: example-daemonset
    spec:
      # nodeselctor #specify if you want to run on specific nodes
      containers:
      - name: example-daemonset
        image: busybox
        args:
        - /bin/sh
        - -c
        - date; sleep 1000
        resources:
          limits:
            memory: 200Mi
          requests: 
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
          
        
