
apiVersion: v1
kind: Pod
metadata:
  name: homepage-dev
  labels:
   env: Development
   author: Sagar
   application_type: ui
   release-version: "1.0"
spec:
  containers:
  - name: helloworld
    image: karthequian/helloworld:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: homepage-staging
  labels:
   env: Staging
   author: Sagar
   application_type: ui
   release-version: "1.0"
spec:
  containers:
  - name: helloworld
    image: karthequian/helloworld:latest
---

apiVersion: v1
kind: Pod
metadata:
  name: homepage-prod
  labels:
   env: Production
   author: Sagar
   application_type: ui
   release-version: "1.0"
spec:
  containers:
  - name: helloworld
    image: karthequian/helloworld:latest
