apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper-SFS
spec:
  serviceName: zookeeper-svc
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
     labels:
       app: zk   
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoreDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                - none
          topologykey: "kubernetes.io/hostname"
     containers:
     - name: kubernetes-zookeeper
       imagePullPolicy: Always
       image: "gcr.io/google_containers/kubernetes-zookeeper:1.0-3.4.10"
       resources:
         requests:
           memory: "500Mi"
           cpu: "0.5"
       ports:
       - containerPort: 2181
         name: client
       - containerPort: 2888
         name: server
       - containerPort: 3888
         name: leader-election
       command:
       - sh
       - -c
       - "start-zookeeper \
         --servers=1 \
         --data_dir=/var/lib/zookeeper/data \
         --data_log_dir=/var/lib/zookeeper/data/log \
         --conf_dir=/opt/zookeeper/conf \
         --client_port=2181 \
         --election_port=3888 \
         --server_port=2888 \
         --tick_time=2000 \
 


